# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0060d2c5b3568b4b96d90b2fcfdf51cc0015c815d79f180dc85849819b76faefd519528c5067762c9222cc8e037ec5951ad7015b9dfe368ae793631577df6584

test:
  secret_key_base: 4322b6edb73ce4f7b43d9eeda15f2f8ff5b724c5274b311ce3aa4646b6f68af7d79d14d97a19d813c868d453589519a521610e4d3f99c07ba044118816cc0f50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
